### ISSUE TITLE
Detected blocking call to import_module

### ISSUE THREAD

**Issue by dhover** [Olen/homeassistant-plant#206]
In HA 2024.11.3 the following error occurs:
```
2024-12-01 14:43:48.261 WARNING (MainThread) [homeassistant.util.loop] Detected blocking call to import_module with args ('custom_components.plant.group',) in /usr/src/homeassistant/homeassistant/loader.py, line 1300: return importlib.import_module(f"{self.pkg_path}.{platform_name}") inside the event loop; This is causing stability issues. Please create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module>
    sys.exit(main())
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main
    exit_code = runner.run(runtime_conf)
  File "/usr/src/homeassistant/homeassistant/runner.py", line 189, in run
    return loop.run_until_complete(setup_and_run_hass(runtime_config))
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete
    self.run_forever()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once
    handle._run()
  File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/src/homeassistant/homeassistant/helpers/integration_platform.py", line 108, in _async_process_integration_platforms_for_component
    platforms = await integration.async_get_platforms(platforms_that_exist)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1169, in async_get_platforms
    platforms.update(self._load_platforms(platform_names))
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1094, in _load_platforms
    platform_name: self._load_platform(platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1268, in _load_platform
    cache[full_name] = self._import_platform(platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1300, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
```

**Comment by Olen** [comment]
Should be fixed in 2024.11.0

**Comment by dhover** [comment]
That's strange. I'm using 2024.11.3 (a newer version). I've restarted HA and the error is still there.

**Comment by Olen** [comment]
2024.11.0 of this integration (that was released about 10 minutes ago).
It has been fixed in the last beta of the integration for a while already, I just have not made a "stable" release until now.

**Comment by dhover** [comment]
Ah I understand. I can confirm the errors are gone now. Thanks.

**Comment by dhover** [comment]
See https://github.com/home-assistant/core/issues/132002
